// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef HWPE_CTRL_TARGET_H
#define HWPE_CTRL_TARGET_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

#if defined(__cplusplus)
#define REDMULE_STATIC_ASSERT(cond, msg) static_assert(cond, msg)
#elif defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
#define REDMULE_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
#else
#define REDMULE_STATIC_ASSERT_CONCAT_(a, b) a##b
#define REDMULE_STATIC_ASSERT_CONCAT(a, b) REDMULE_STATIC_ASSERT_CONCAT_(a, b)
#define REDMULE_STATIC_ASSERT(cond, msg) \
  typedef char REDMULE_STATIC_ASSERT_CONCAT(redmule_static_assert_, __LINE__)[(cond) ? 1 : -1]
#endif

// reg - redmule_regif::hwpe_commit_trigger
#define REDMULE_REGIF__HWPE_COMMIT_TRIGGER__COMMIT_TRIGGER_bm 0x3
#define REDMULE_REGIF__HWPE_COMMIT_TRIGGER__COMMIT_TRIGGER_bp 0
#define REDMULE_REGIF__HWPE_COMMIT_TRIGGER__COMMIT_TRIGGER_bw 2
#define REDMULE_REGIF__HWPE_COMMIT_TRIGGER__COMMIT_TRIGGER_reset 0x0
#define REDMULE_REGIF__HWPE_COMMIT_TRIGGER__R0_bm 0xfffffffc
#define REDMULE_REGIF__HWPE_COMMIT_TRIGGER__R0_bp 2
#define REDMULE_REGIF__HWPE_COMMIT_TRIGGER__R0_bw 30
#define REDMULE_REGIF__HWPE_COMMIT_TRIGGER__R0_reset 0x0

// reg - redmule_regif::hwpe_acquire
#define REDMULE_REGIF__HWPE_ACQUIRE__ACQUIRE_bm 0xffffffff
#define REDMULE_REGIF__HWPE_ACQUIRE__ACQUIRE_bp 0
#define REDMULE_REGIF__HWPE_ACQUIRE__ACQUIRE_bw 32
#define REDMULE_REGIF__HWPE_ACQUIRE__ACQUIRE_reset 0x0

// reg - redmule_regif::hwpe_reserved
#define REDMULE_REGIF__HWPE_RESERVED__RESERVED_bm 0xffffffff
#define REDMULE_REGIF__HWPE_RESERVED__RESERVED_bp 0
#define REDMULE_REGIF__HWPE_RESERVED__RESERVED_bw 32
#define REDMULE_REGIF__HWPE_RESERVED__RESERVED_reset 0x0

// reg - redmule_regif::hwpe_status
#define REDMULE_REGIF__HWPE_STATUS__STATUS0_bm 0xffffffff
#define REDMULE_REGIF__HWPE_STATUS__STATUS0_bp 0
#define REDMULE_REGIF__HWPE_STATUS__STATUS0_bw 32
#define REDMULE_REGIF__HWPE_STATUS__STATUS0_reset 0x0

// reg - redmule_regif::hwpe_running_job
#define REDMULE_REGIF__HWPE_RUNNING_JOB__RUNNING_JOB_bm 0xff
#define REDMULE_REGIF__HWPE_RUNNING_JOB__RUNNING_JOB_bp 0
#define REDMULE_REGIF__HWPE_RUNNING_JOB__RUNNING_JOB_bw 8
#define REDMULE_REGIF__HWPE_RUNNING_JOB__RUNNING_JOB_reset 0x0
#define REDMULE_REGIF__HWPE_RUNNING_JOB__R0_bm 0xffffff00
#define REDMULE_REGIF__HWPE_RUNNING_JOB__R0_bp 8
#define REDMULE_REGIF__HWPE_RUNNING_JOB__R0_bw 24
#define REDMULE_REGIF__HWPE_RUNNING_JOB__R0_reset 0x0

// reg - redmule_regif::hwpe_soft_clear
#define REDMULE_REGIF__HWPE_SOFT_CLEAR__SOFT_CLEAR_bm 0x3
#define REDMULE_REGIF__HWPE_SOFT_CLEAR__SOFT_CLEAR_bp 0
#define REDMULE_REGIF__HWPE_SOFT_CLEAR__SOFT_CLEAR_bw 2
#define REDMULE_REGIF__HWPE_SOFT_CLEAR__SOFT_CLEAR_reset 0x0
#define REDMULE_REGIF__HWPE_SOFT_CLEAR__R0_bm 0xfffffffc
#define REDMULE_REGIF__HWPE_SOFT_CLEAR__R0_bp 2
#define REDMULE_REGIF__HWPE_SOFT_CLEAR__R0_bw 30
#define REDMULE_REGIF__HWPE_SOFT_CLEAR__R0_reset 0x0

// regfile - redmule_regif::hwpe_ctrl_mandatory
typedef struct __attribute__ ((__packed__)) {
    uint32_t commit_trigger;
    uint32_t acquire;
    uint32_t reserved0;
    uint32_t status;
    uint32_t running_job;
    uint32_t soft_clear;
    uint32_t reserved1;
    uint32_t reserved2;
} redmule_regif__hwpe_ctrl_mandatory_t;

// reg - redmule_regif::mcnfig0
#define REDMULE_REGIF__MCNFIG0__M_SIZE_bm 0xffff
#define REDMULE_REGIF__MCNFIG0__M_SIZE_bp 0
#define REDMULE_REGIF__MCNFIG0__M_SIZE_bw 16
#define REDMULE_REGIF__MCNFIG0__M_SIZE_reset 0x0
#define REDMULE_REGIF__MCNFIG0__K_SIZE_bm 0xffff0000
#define REDMULE_REGIF__MCNFIG0__K_SIZE_bp 16
#define REDMULE_REGIF__MCNFIG0__K_SIZE_bw 16
#define REDMULE_REGIF__MCNFIG0__K_SIZE_reset 0x0

// reg - redmule_regif::mcnfig1
#define REDMULE_REGIF__MCNFIG1__N_SIZE_bm 0xffff
#define REDMULE_REGIF__MCNFIG1__N_SIZE_bp 0
#define REDMULE_REGIF__MCNFIG1__N_SIZE_bw 16
#define REDMULE_REGIF__MCNFIG1__N_SIZE_reset 0x0
#define REDMULE_REGIF__MCNFIG1__RECEIVE_X_bm 0x10000
#define REDMULE_REGIF__MCNFIG1__RECEIVE_X_bp 16
#define REDMULE_REGIF__MCNFIG1__RECEIVE_X_bw 1
#define REDMULE_REGIF__MCNFIG1__RECEIVE_X_reset 0x0
#define REDMULE_REGIF__MCNFIG1__SEND_X_bm 0x20000
#define REDMULE_REGIF__MCNFIG1__SEND_X_bp 17
#define REDMULE_REGIF__MCNFIG1__SEND_X_bw 1
#define REDMULE_REGIF__MCNFIG1__SEND_X_reset 0x0
#define REDMULE_REGIF__MCNFIG1__RECEIVE_W_bm 0x40000
#define REDMULE_REGIF__MCNFIG1__RECEIVE_W_bp 18
#define REDMULE_REGIF__MCNFIG1__RECEIVE_W_bw 1
#define REDMULE_REGIF__MCNFIG1__RECEIVE_W_reset 0x0
#define REDMULE_REGIF__MCNFIG1__SEND_W_bm 0x80000
#define REDMULE_REGIF__MCNFIG1__SEND_W_bp 19
#define REDMULE_REGIF__MCNFIG1__SEND_W_bw 1
#define REDMULE_REGIF__MCNFIG1__SEND_W_reset 0x0
#define REDMULE_REGIF__MCNFIG1__GEMM_OPS_bm 0x700000
#define REDMULE_REGIF__MCNFIG1__GEMM_OPS_bp 20
#define REDMULE_REGIF__MCNFIG1__GEMM_OPS_bw 3
#define REDMULE_REGIF__MCNFIG1__GEMM_OPS_reset 0x0
#define REDMULE_REGIF__MCNFIG1__GEMM_INPUT_FMT_bm 0x1800000
#define REDMULE_REGIF__MCNFIG1__GEMM_INPUT_FMT_bp 23
#define REDMULE_REGIF__MCNFIG1__GEMM_INPUT_FMT_bw 2
#define REDMULE_REGIF__MCNFIG1__GEMM_INPUT_FMT_reset 0x0
#define REDMULE_REGIF__MCNFIG1__GEMM_OUTPUT_FMT_bm 0x6000000
#define REDMULE_REGIF__MCNFIG1__GEMM_OUTPUT_FMT_bp 25
#define REDMULE_REGIF__MCNFIG1__GEMM_OUTPUT_FMT_bw 2
#define REDMULE_REGIF__MCNFIG1__GEMM_OUTPUT_FMT_reset 0x0

// reg - redmule_regif::mcnfig2
#define REDMULE_REGIF__MCNFIG2__Y_OFFS_bm 0xffffffff
#define REDMULE_REGIF__MCNFIG2__Y_OFFS_bp 0
#define REDMULE_REGIF__MCNFIG2__Y_OFFS_bw 32
#define REDMULE_REGIF__MCNFIG2__Y_OFFS_reset 0x0

// reg - redmule_regif::marith0
#define REDMULE_REGIF__MARITH0__X_ADDR_bm 0xffffffff
#define REDMULE_REGIF__MARITH0__X_ADDR_bp 0
#define REDMULE_REGIF__MARITH0__X_ADDR_bw 32
#define REDMULE_REGIF__MARITH0__X_ADDR_reset 0x0

// reg - redmule_regif::marith1
#define REDMULE_REGIF__MARITH1__W_ADDR_bm 0xffffffff
#define REDMULE_REGIF__MARITH1__W_ADDR_bp 0
#define REDMULE_REGIF__MARITH1__W_ADDR_bw 32
#define REDMULE_REGIF__MARITH1__W_ADDR_reset 0x0

// reg - redmule_regif::marith2
#define REDMULE_REGIF__MARITH2__Z_ADDR_bm 0xffffffff
#define REDMULE_REGIF__MARITH2__Z_ADDR_bp 0
#define REDMULE_REGIF__MARITH2__Z_ADDR_bw 32
#define REDMULE_REGIF__MARITH2__Z_ADDR_reset 0x0

// reg - redmule_regif::mopcnt
#define REDMULE_REGIF__MOPCNT__OP_ID_CNT_bm 0xffffffff
#define REDMULE_REGIF__MOPCNT__OP_ID_CNT_bp 0
#define REDMULE_REGIF__MOPCNT__OP_ID_CNT_bw 32
#define REDMULE_REGIF__MOPCNT__OP_ID_CNT_reset 0x0

// reg - redmule_regif::mcnfig3
#define REDMULE_REGIF__MCNFIG3__W_COLS_OFFSET_bm 0xffffffff
#define REDMULE_REGIF__MCNFIG3__W_COLS_OFFSET_bp 0
#define REDMULE_REGIF__MCNFIG3__W_COLS_OFFSET_bw 32
#define REDMULE_REGIF__MCNFIG3__W_COLS_OFFSET_reset 0x0

// regfile - redmule_regif::hwpe_ctrl_job_dep
typedef struct __attribute__ ((__packed__)) {
    uint32_t mcnfig0;
    uint32_t mcnfig1;
    uint32_t mcnfig2;
    uint32_t marith0;
    uint32_t marith1;
    uint32_t marith2;
    uint32_t mopcnt;
    uint32_t mcnfig3;
} redmule_regif__hwpe_ctrl_job_dep_t;

// regfile - redmule_regif::hwpe_ctrl_job_indep
typedef struct __attribute__ ((__packed__)) {
    uint32_t reserved;
} redmule_regif__hwpe_ctrl_job_indep_t;

// addrmap - redmule_regif
typedef struct __attribute__ ((__packed__)) {
    redmule_regif__hwpe_ctrl_mandatory_t hwpe_ctrl;
    redmule_regif__hwpe_ctrl_job_dep_t hwpe_job_dep;
    redmule_regif__hwpe_ctrl_job_indep_t hwpe_job_indep;
} redmule_regif_t;


REDMULE_STATIC_ASSERT(sizeof(redmule_regif_t) == 0x44, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* HWPE_CTRL_TARGET_H */
