# 
# Copyright (C) 2022-2023 ETH Zurich and University of Bologna
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Yvan Tortorella (yvan.tortorella@unibo.it)
#
# Makefile for ipstools dependencies handling

.PHONY: build lib clean 

mkfile_path := $(dir $(abspath $(firstword $(MAKEFILE_LIST))))

all: clean lib build opt

sim:
	vsim vopt_tb

opt:
	$(mkfile_path)/tcl_files/rtl_vopt.tcl

build:
	@make --no-print-directory -f $(mkfile_path)/vcompile/ips.mk build
	@make --no-print-directory -f $(mkfile_path)/vcompile/rtl.mk build

lib:
	mkdir -p work
	vlib work
	vmap work work
	@make --no-print-directory -f $(mkfile_path)/vcompile/ips.mk lib
	@make --no-print-directory -f $(mkfile_path)/vcompile/rtl.mk lib

clean:
	@make --no-print-directory -f $(mkfile_path)/vcompile/ips.mk clean
	@make --no-print-directory -f $(mkfile_path)/vcompile/rtl.mk clean
	rm -rf work
