// Copyright 2025 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module redmule_regif (
        input wire clk,
        input wire arst_n,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [31:0] s_cpuif_addr,
        input wire [31:0] s_cpuif_wr_data,
        input wire [31:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [31:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        input redmule_regif_pkg::redmule_regif__in_t hwif_in,
        output redmule_regif_pkg::redmule_regif__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [31:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            logic commit_trigger;
            logic acquire;
            logic autotrigger;
            logic status;
            logic running_job;
            logic soft_clear;
            logic reserved1;
            logic reserved2;
        } hwpe_ctrl;
        struct {
            logic mcnfig0;
            logic mcnfig1;
            logic mcnfig2;
            logic marith0;
            logic marith1;
            logic marith2;
            logic mopcnt;
            logic mcnfig3;
        } hwpe_job_dep;
        struct {
            logic reserved;
        } hwpe_job_indep;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [31:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.hwpe_ctrl.commit_trigger = cpuif_req_masked & (cpuif_addr == 32'h0);
        decoded_reg_strb.hwpe_ctrl.acquire = cpuif_req_masked & (cpuif_addr == 32'h4) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.autotrigger = cpuif_req_masked & (cpuif_addr == 32'h8);
        decoded_reg_strb.hwpe_ctrl.status = cpuif_req_masked & (cpuif_addr == 32'hc) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.running_job = cpuif_req_masked & (cpuif_addr == 32'h10) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.soft_clear = cpuif_req_masked & (cpuif_addr == 32'h14);
        decoded_reg_strb.hwpe_ctrl.reserved1 = cpuif_req_masked & (cpuif_addr == 32'h18) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.reserved2 = cpuif_req_masked & (cpuif_addr == 32'h1c) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_job_dep.mcnfig0 = cpuif_req_masked & (cpuif_addr == 32'h20);
        decoded_reg_strb.hwpe_job_dep.mcnfig1 = cpuif_req_masked & (cpuif_addr == 32'h24);
        decoded_reg_strb.hwpe_job_dep.mcnfig2 = cpuif_req_masked & (cpuif_addr == 32'h28);
        decoded_reg_strb.hwpe_job_dep.marith0 = cpuif_req_masked & (cpuif_addr == 32'h2c);
        decoded_reg_strb.hwpe_job_dep.marith1 = cpuif_req_masked & (cpuif_addr == 32'h30);
        decoded_reg_strb.hwpe_job_dep.marith2 = cpuif_req_masked & (cpuif_addr == 32'h34);
        decoded_reg_strb.hwpe_job_dep.mopcnt = cpuif_req_masked & (cpuif_addr == 32'h38) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_job_dep.mcnfig3 = cpuif_req_masked & (cpuif_addr == 32'h3c);
        decoded_reg_strb.hwpe_job_indep.reserved = cpuif_req_masked & (cpuif_addr == 32'h40) & !cpuif_req_is_wr;
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } commit_trigger;
            } commit_trigger;
            struct {
                struct {
                    logic next;
                    logic load_next;
                } autotrigger_n;
            } autotrigger;
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } soft_clear;
            } soft_clear;
        } hwpe_ctrl;
        struct {
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } m_size;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } k_size;
            } mcnfig0;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } n_size;
                struct {
                    logic next;
                    logic load_next;
                } receive_x;
                struct {
                    logic next;
                    logic load_next;
                } send_x;
                struct {
                    logic next;
                    logic load_next;
                } receive_w;
                struct {
                    logic next;
                    logic load_next;
                } send_w;
                struct {
                    logic [2:0] next;
                    logic load_next;
                } gemm_ops;
                struct {
                    logic [1:0] next;
                    logic load_next;
                } gemm_input_fmt;
                struct {
                    logic [1:0] next;
                    logic load_next;
                } gemm_output_fmt;
            } mcnfig1;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } y_offs;
            } mcnfig2;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } x_addr;
            } marith0;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } w_addr;
            } marith1;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } z_addr;
            } marith2;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } w_cols_offset;
            } mcnfig3;
        } hwpe_job_dep;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] value;
                } commit_trigger;
            } commit_trigger;
            struct {
                struct {
                    logic value;
                } autotrigger_n;
            } autotrigger;
            struct {
                struct {
                    logic [1:0] value;
                } soft_clear;
            } soft_clear;
        } hwpe_ctrl;
        struct {
            struct {
                struct {
                    logic [15:0] value;
                } m_size;
                struct {
                    logic [15:0] value;
                } k_size;
            } mcnfig0;
            struct {
                struct {
                    logic [15:0] value;
                } n_size;
                struct {
                    logic value;
                } receive_x;
                struct {
                    logic value;
                } send_x;
                struct {
                    logic value;
                } receive_w;
                struct {
                    logic value;
                } send_w;
                struct {
                    logic [2:0] value;
                } gemm_ops;
                struct {
                    logic [1:0] value;
                } gemm_input_fmt;
                struct {
                    logic [1:0] value;
                } gemm_output_fmt;
            } mcnfig1;
            struct {
                struct {
                    logic [31:0] value;
                } y_offs;
            } mcnfig2;
            struct {
                struct {
                    logic [31:0] value;
                } x_addr;
            } marith0;
            struct {
                struct {
                    logic [31:0] value;
                } w_addr;
            } marith1;
            struct {
                struct {
                    logic [31:0] value;
                } z_addr;
            } marith2;
            struct {
                struct {
                    logic [31:0] value;
                } w_cols_offset;
            } mcnfig3;
        } hwpe_job_dep;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: redmule_regif.hwpe_ctrl.commit_trigger.commit_trigger
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_ctrl.commit_trigger && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_ctrl.commit_trigger.commit_trigger.next = next_c;
        field_combo.hwpe_ctrl.commit_trigger.commit_trigger.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_ctrl.commit_trigger.commit_trigger.load_next) begin
                field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value <= field_combo.hwpe_ctrl.commit_trigger.commit_trigger.next;
            end
        end
    end
    assign hwif_out.hwpe_ctrl.commit_trigger.commit_trigger.value = field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value;
    assign hwif_out.hwpe_ctrl.commit_trigger.commit_trigger.swacc = decoded_reg_strb.hwpe_ctrl.commit_trigger;
    assign hwif_out.hwpe_ctrl.commit_trigger.r0.value = 30'h0;
    assign hwif_out.hwpe_ctrl.acquire.acquire.swacc = decoded_reg_strb.hwpe_ctrl.acquire;
    // Field: redmule_regif.hwpe_ctrl.autotrigger.autotrigger_n
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_ctrl.autotrigger && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_ctrl.autotrigger.autotrigger_n.next = next_c;
        field_combo.hwpe_ctrl.autotrigger.autotrigger_n.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_ctrl.autotrigger.autotrigger_n.load_next) begin
                field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value <= field_combo.hwpe_ctrl.autotrigger.autotrigger_n.next;
            end
        end
    end
    assign hwif_out.hwpe_ctrl.autotrigger.autotrigger_n.value = field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value;
    assign hwif_out.hwpe_ctrl.autotrigger.r0.value = 31'h0;
    assign hwif_out.hwpe_ctrl.running_job.r0.value = 24'h0;
    // Field: redmule_regif.hwpe_ctrl.soft_clear.soft_clear
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_ctrl.soft_clear.soft_clear.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_ctrl.soft_clear && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_ctrl.soft_clear.soft_clear.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_ctrl.soft_clear.soft_clear.next = next_c;
        field_combo.hwpe_ctrl.soft_clear.soft_clear.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_ctrl.soft_clear.soft_clear.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_ctrl.soft_clear.soft_clear.load_next) begin
                field_storage.hwpe_ctrl.soft_clear.soft_clear.value <= field_combo.hwpe_ctrl.soft_clear.soft_clear.next;
            end
        end
    end
    assign hwif_out.hwpe_ctrl.soft_clear.soft_clear.value = field_storage.hwpe_ctrl.soft_clear.soft_clear.value;
    assign hwif_out.hwpe_ctrl.soft_clear.soft_clear.swacc = decoded_reg_strb.hwpe_ctrl.soft_clear;
    assign hwif_out.hwpe_ctrl.soft_clear.r0.value = 30'h0;
    assign hwif_out.hwpe_ctrl.reserved1.reserved.value = 32'h0;
    assign hwif_out.hwpe_ctrl.reserved2.reserved.value = 32'h0;
    // Field: redmule_regif.hwpe_job_dep.mcnfig0.m_size
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig0.m_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig0.m_size.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig0.m_size.next = next_c;
        field_combo.hwpe_job_dep.mcnfig0.m_size.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig0.m_size.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig0.m_size.load_next) begin
                field_storage.hwpe_job_dep.mcnfig0.m_size.value <= field_combo.hwpe_job_dep.mcnfig0.m_size.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig0.m_size.value = field_storage.hwpe_job_dep.mcnfig0.m_size.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig0.k_size
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig0.k_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig0.k_size.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig0.k_size.next = next_c;
        field_combo.hwpe_job_dep.mcnfig0.k_size.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig0.k_size.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig0.k_size.load_next) begin
                field_storage.hwpe_job_dep.mcnfig0.k_size.value <= field_combo.hwpe_job_dep.mcnfig0.k_size.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig0.k_size.value = field_storage.hwpe_job_dep.mcnfig0.k_size.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig1.n_size
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig1.n_size.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig1.n_size.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig1.n_size.next = next_c;
        field_combo.hwpe_job_dep.mcnfig1.n_size.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig1.n_size.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig1.n_size.load_next) begin
                field_storage.hwpe_job_dep.mcnfig1.n_size.value <= field_combo.hwpe_job_dep.mcnfig1.n_size.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig1.n_size.value = field_storage.hwpe_job_dep.mcnfig1.n_size.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig1.receive_x
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig1.receive_x.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig1.receive_x.value & ~decoded_wr_biten[16:16]) | (decoded_wr_data[16:16] & decoded_wr_biten[16:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig1.receive_x.next = next_c;
        field_combo.hwpe_job_dep.mcnfig1.receive_x.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig1.receive_x.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig1.receive_x.load_next) begin
                field_storage.hwpe_job_dep.mcnfig1.receive_x.value <= field_combo.hwpe_job_dep.mcnfig1.receive_x.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig1.receive_x.value = field_storage.hwpe_job_dep.mcnfig1.receive_x.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig1.send_x
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig1.send_x.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig1.send_x.value & ~decoded_wr_biten[17:17]) | (decoded_wr_data[17:17] & decoded_wr_biten[17:17]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig1.send_x.next = next_c;
        field_combo.hwpe_job_dep.mcnfig1.send_x.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig1.send_x.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig1.send_x.load_next) begin
                field_storage.hwpe_job_dep.mcnfig1.send_x.value <= field_combo.hwpe_job_dep.mcnfig1.send_x.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig1.send_x.value = field_storage.hwpe_job_dep.mcnfig1.send_x.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig1.receive_w
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig1.receive_w.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig1.receive_w.value & ~decoded_wr_biten[18:18]) | (decoded_wr_data[18:18] & decoded_wr_biten[18:18]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig1.receive_w.next = next_c;
        field_combo.hwpe_job_dep.mcnfig1.receive_w.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig1.receive_w.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig1.receive_w.load_next) begin
                field_storage.hwpe_job_dep.mcnfig1.receive_w.value <= field_combo.hwpe_job_dep.mcnfig1.receive_w.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig1.receive_w.value = field_storage.hwpe_job_dep.mcnfig1.receive_w.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig1.send_w
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig1.send_w.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig1.send_w.value & ~decoded_wr_biten[19:19]) | (decoded_wr_data[19:19] & decoded_wr_biten[19:19]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig1.send_w.next = next_c;
        field_combo.hwpe_job_dep.mcnfig1.send_w.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig1.send_w.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig1.send_w.load_next) begin
                field_storage.hwpe_job_dep.mcnfig1.send_w.value <= field_combo.hwpe_job_dep.mcnfig1.send_w.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig1.send_w.value = field_storage.hwpe_job_dep.mcnfig1.send_w.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig1.gemm_ops
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig1.gemm_ops.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig1.gemm_ops.value & ~decoded_wr_biten[22:20]) | (decoded_wr_data[22:20] & decoded_wr_biten[22:20]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig1.gemm_ops.next = next_c;
        field_combo.hwpe_job_dep.mcnfig1.gemm_ops.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig1.gemm_ops.value <= 3'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig1.gemm_ops.load_next) begin
                field_storage.hwpe_job_dep.mcnfig1.gemm_ops.value <= field_combo.hwpe_job_dep.mcnfig1.gemm_ops.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig1.gemm_ops.value = field_storage.hwpe_job_dep.mcnfig1.gemm_ops.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig1.gemm_input_fmt
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig1.gemm_input_fmt.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig1.gemm_input_fmt.value & ~decoded_wr_biten[24:23]) | (decoded_wr_data[24:23] & decoded_wr_biten[24:23]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig1.gemm_input_fmt.next = next_c;
        field_combo.hwpe_job_dep.mcnfig1.gemm_input_fmt.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig1.gemm_input_fmt.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig1.gemm_input_fmt.load_next) begin
                field_storage.hwpe_job_dep.mcnfig1.gemm_input_fmt.value <= field_combo.hwpe_job_dep.mcnfig1.gemm_input_fmt.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig1.gemm_input_fmt.value = field_storage.hwpe_job_dep.mcnfig1.gemm_input_fmt.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig1.gemm_output_fmt
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig1.gemm_output_fmt.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig1.gemm_output_fmt.value & ~decoded_wr_biten[26:25]) | (decoded_wr_data[26:25] & decoded_wr_biten[26:25]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig1.gemm_output_fmt.next = next_c;
        field_combo.hwpe_job_dep.mcnfig1.gemm_output_fmt.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig1.gemm_output_fmt.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig1.gemm_output_fmt.load_next) begin
                field_storage.hwpe_job_dep.mcnfig1.gemm_output_fmt.value <= field_combo.hwpe_job_dep.mcnfig1.gemm_output_fmt.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig1.gemm_output_fmt.value = field_storage.hwpe_job_dep.mcnfig1.gemm_output_fmt.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig2.y_offs
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig2.y_offs.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig2.y_offs.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig2.y_offs.next = next_c;
        field_combo.hwpe_job_dep.mcnfig2.y_offs.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig2.y_offs.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig2.y_offs.load_next) begin
                field_storage.hwpe_job_dep.mcnfig2.y_offs.value <= field_combo.hwpe_job_dep.mcnfig2.y_offs.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig2.y_offs.value = field_storage.hwpe_job_dep.mcnfig2.y_offs.value;
    // Field: redmule_regif.hwpe_job_dep.marith0.x_addr
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.marith0.x_addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.marith0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.marith0.x_addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.marith0.x_addr.next = next_c;
        field_combo.hwpe_job_dep.marith0.x_addr.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.marith0.x_addr.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.marith0.x_addr.load_next) begin
                field_storage.hwpe_job_dep.marith0.x_addr.value <= field_combo.hwpe_job_dep.marith0.x_addr.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.marith0.x_addr.value = field_storage.hwpe_job_dep.marith0.x_addr.value;
    // Field: redmule_regif.hwpe_job_dep.marith1.w_addr
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.marith1.w_addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.marith1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.marith1.w_addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.marith1.w_addr.next = next_c;
        field_combo.hwpe_job_dep.marith1.w_addr.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.marith1.w_addr.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.marith1.w_addr.load_next) begin
                field_storage.hwpe_job_dep.marith1.w_addr.value <= field_combo.hwpe_job_dep.marith1.w_addr.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.marith1.w_addr.value = field_storage.hwpe_job_dep.marith1.w_addr.value;
    // Field: redmule_regif.hwpe_job_dep.marith2.z_addr
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.marith2.z_addr.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.marith2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.marith2.z_addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.marith2.z_addr.next = next_c;
        field_combo.hwpe_job_dep.marith2.z_addr.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.marith2.z_addr.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.marith2.z_addr.load_next) begin
                field_storage.hwpe_job_dep.marith2.z_addr.value <= field_combo.hwpe_job_dep.marith2.z_addr.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.marith2.z_addr.value = field_storage.hwpe_job_dep.marith2.z_addr.value;
    // Field: redmule_regif.hwpe_job_dep.mcnfig3.w_cols_offset
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.mcnfig3.w_cols_offset.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.mcnfig3 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.mcnfig3.w_cols_offset.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.mcnfig3.w_cols_offset.next = next_c;
        field_combo.hwpe_job_dep.mcnfig3.w_cols_offset.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.mcnfig3.w_cols_offset.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.mcnfig3.w_cols_offset.load_next) begin
                field_storage.hwpe_job_dep.mcnfig3.w_cols_offset.value <= field_combo.hwpe_job_dep.mcnfig3.w_cols_offset.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.mcnfig3.w_cols_offset.value = field_storage.hwpe_job_dep.mcnfig3.w_cols_offset.value;
    assign hwif_out.hwpe_job_indep.reserved.reserved.value = 32'h0;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [31:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 32'h0) begin
            readback_data_var[31:2] = 30'h0;
        end
        if(rd_mux_addr == 32'h4) begin
            readback_data_var[31:0] = hwif_in.hwpe_ctrl.acquire.acquire.next;
        end
        if(rd_mux_addr == 32'h8) begin
            readback_data_var[0] = field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value;
            readback_data_var[31:1] = 31'h0;
        end
        if(rd_mux_addr == 32'hc) begin
            readback_data_var[31:0] = hwif_in.hwpe_ctrl.status.status0.next;
        end
        if(rd_mux_addr == 32'h10) begin
            readback_data_var[7:0] = hwif_in.hwpe_ctrl.running_job.running_job.next;
            readback_data_var[31:8] = 24'h0;
        end
        if(rd_mux_addr == 32'h14) begin
            readback_data_var[31:2] = 30'h0;
        end
        if(rd_mux_addr == 32'h18) begin
            readback_data_var[31:0] = 32'h0;
        end
        if(rd_mux_addr == 32'h1c) begin
            readback_data_var[31:0] = 32'h0;
        end
        if(rd_mux_addr == 32'h20) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.mcnfig0.m_size.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.mcnfig0.k_size.value;
        end
        if(rd_mux_addr == 32'h24) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.mcnfig1.n_size.value;
            readback_data_var[16] = field_storage.hwpe_job_dep.mcnfig1.receive_x.value;
            readback_data_var[17] = field_storage.hwpe_job_dep.mcnfig1.send_x.value;
            readback_data_var[18] = field_storage.hwpe_job_dep.mcnfig1.receive_w.value;
            readback_data_var[19] = field_storage.hwpe_job_dep.mcnfig1.send_w.value;
            readback_data_var[22:20] = field_storage.hwpe_job_dep.mcnfig1.gemm_ops.value;
            readback_data_var[24:23] = field_storage.hwpe_job_dep.mcnfig1.gemm_input_fmt.value;
            readback_data_var[26:25] = field_storage.hwpe_job_dep.mcnfig1.gemm_output_fmt.value;
        end
        if(rd_mux_addr == 32'h28) begin
            readback_data_var[31:0] = field_storage.hwpe_job_dep.mcnfig2.y_offs.value;
        end
        if(rd_mux_addr == 32'h2c) begin
            readback_data_var[31:0] = field_storage.hwpe_job_dep.marith0.x_addr.value;
        end
        if(rd_mux_addr == 32'h30) begin
            readback_data_var[31:0] = field_storage.hwpe_job_dep.marith1.w_addr.value;
        end
        if(rd_mux_addr == 32'h34) begin
            readback_data_var[31:0] = field_storage.hwpe_job_dep.marith2.z_addr.value;
        end
        if(rd_mux_addr == 32'h38) begin
            readback_data_var[31:0] = hwif_in.hwpe_job_dep.mopcnt.op_id_cnt.next;
        end
        if(rd_mux_addr == 32'h3c) begin
            readback_data_var[31:0] = field_storage.hwpe_job_dep.mcnfig3.w_cols_offset.value;
        end
        if(rd_mux_addr == 32'h40) begin
            readback_data_var[31:0] = 32'h0;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
