// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package redmule_regif_pkg;

    localparam REDMULE_REGIF_DATA_WIDTH = 32;
    localparam REDMULE_REGIF_MIN_ADDR_WIDTH = 32;
    localparam REDMULE_REGIF_SIZE = 'h40;

    typedef struct packed {
        logic [31:0] next;
    } redmule_regif__hwpe_acquire__acquire__in_t;

    typedef struct packed {
        redmule_regif__hwpe_acquire__acquire__in_t acquire;
    } redmule_regif__hwpe_acquire__in_t;

    typedef struct packed {
        logic [31:0] next;
    } redmule_regif__hwpe_status__status0__in_t;

    typedef struct packed {
        redmule_regif__hwpe_status__status0__in_t status0;
    } redmule_regif__hwpe_status__in_t;

    typedef struct packed {
        logic [7:0] next;
    } redmule_regif__hwpe_running_job__running_job__in_t;

    typedef struct packed {
        redmule_regif__hwpe_running_job__running_job__in_t running_job;
    } redmule_regif__hwpe_running_job__in_t;

    typedef struct packed {
        redmule_regif__hwpe_acquire__in_t acquire;
        redmule_regif__hwpe_status__in_t status;
        redmule_regif__hwpe_running_job__in_t running_job;
    } redmule_regif__hwpe_ctrl_mandatory__in_t;

    typedef struct packed {
        logic [31:0] next;
    } redmule_regif__mopcnt__op_id_cnt__in_t;

    typedef struct packed {
        redmule_regif__mopcnt__op_id_cnt__in_t op_id_cnt;
    } redmule_regif__mopcnt__in_t;

    typedef struct packed {
        redmule_regif__mopcnt__in_t mopcnt;
    } redmule_regif__hwpe_ctrl_job_dep__in_t;

    typedef struct packed {
        redmule_regif__hwpe_ctrl_mandatory__in_t hwpe_ctrl;
        redmule_regif__hwpe_ctrl_job_dep__in_t hwpe_job_dep;
    } redmule_regif__in_t;

    typedef struct packed {
        logic [1:0] value;
        logic swacc;
    } redmule_regif__hwpe_commit_trigger__commit_trigger__out_t;

    typedef struct packed {
        logic [29:0] value;
    } redmule_regif__hwpe_commit_trigger__r0__out_t;

    typedef struct packed {
        redmule_regif__hwpe_commit_trigger__commit_trigger__out_t commit_trigger;
        redmule_regif__hwpe_commit_trigger__r0__out_t r0;
    } redmule_regif__hwpe_commit_trigger__out_t;

    typedef struct packed {
        logic swacc;
    } redmule_regif__hwpe_acquire__acquire__out_t;

    typedef struct packed {
        redmule_regif__hwpe_acquire__acquire__out_t acquire;
    } redmule_regif__hwpe_acquire__out_t;

    typedef struct packed {
        logic [31:0] value;
    } redmule_regif__hwpe_reserved__reserved__out_t;

    typedef struct packed {
        redmule_regif__hwpe_reserved__reserved__out_t reserved;
    } redmule_regif__hwpe_reserved__out_t;

    typedef struct packed {
        logic [23:0] value;
    } redmule_regif__hwpe_running_job__r0__out_t;

    typedef struct packed {
        redmule_regif__hwpe_running_job__r0__out_t r0;
    } redmule_regif__hwpe_running_job__out_t;

    typedef struct packed {
        logic [1:0] value;
        logic swacc;
    } redmule_regif__hwpe_soft_clear__soft_clear__out_t;

    typedef struct packed {
        logic [29:0] value;
    } redmule_regif__hwpe_soft_clear__r0__out_t;

    typedef struct packed {
        redmule_regif__hwpe_soft_clear__soft_clear__out_t soft_clear;
        redmule_regif__hwpe_soft_clear__r0__out_t r0;
    } redmule_regif__hwpe_soft_clear__out_t;

    typedef struct packed {
        redmule_regif__hwpe_commit_trigger__out_t commit_trigger;
        redmule_regif__hwpe_acquire__out_t acquire;
        redmule_regif__hwpe_reserved__out_t reserved0;
        redmule_regif__hwpe_running_job__out_t running_job;
        redmule_regif__hwpe_soft_clear__out_t soft_clear;
        redmule_regif__hwpe_reserved__out_t reserved1;
        redmule_regif__hwpe_reserved__out_t reserved2;
    } redmule_regif__hwpe_ctrl_mandatory__out_t;

    typedef struct packed {
        logic [15:0] value;
    } redmule_regif__mcnfig0__m_size__out_t;

    typedef struct packed {
        logic [15:0] value;
    } redmule_regif__mcnfig0__k_size__out_t;

    typedef struct packed {
        redmule_regif__mcnfig0__m_size__out_t m_size;
        redmule_regif__mcnfig0__k_size__out_t k_size;
    } redmule_regif__mcnfig0__out_t;

    typedef struct packed {
        logic [15:0] value;
    } redmule_regif__mcnfig1__n_size__out_t;

    typedef struct packed {
        logic value;
    } redmule_regif__mcnfig1__receive_x__out_t;

    typedef struct packed {
        logic value;
    } redmule_regif__mcnfig1__send_x__out_t;

    typedef struct packed {
        logic value;
    } redmule_regif__mcnfig1__receive_w__out_t;

    typedef struct packed {
        logic value;
    } redmule_regif__mcnfig1__send_w__out_t;

    typedef struct packed {
        logic [2:0] value;
    } redmule_regif__mcnfig1__gemm_ops__out_t;

    typedef struct packed {
        logic [1:0] value;
    } redmule_regif__mcnfig1__gemm_input_fmt__out_t;

    typedef struct packed {
        logic [1:0] value;
    } redmule_regif__mcnfig1__gemm_output_fmt__out_t;

    typedef struct packed {
        redmule_regif__mcnfig1__n_size__out_t n_size;
        redmule_regif__mcnfig1__receive_x__out_t receive_x;
        redmule_regif__mcnfig1__send_x__out_t send_x;
        redmule_regif__mcnfig1__receive_w__out_t receive_w;
        redmule_regif__mcnfig1__send_w__out_t send_w;
        redmule_regif__mcnfig1__gemm_ops__out_t gemm_ops;
        redmule_regif__mcnfig1__gemm_input_fmt__out_t gemm_input_fmt;
        redmule_regif__mcnfig1__gemm_output_fmt__out_t gemm_output_fmt;
    } redmule_regif__mcnfig1__out_t;

    typedef struct packed {
        logic [31:0] value;
    } redmule_regif__mcnfig2__y_offs__out_t;

    typedef struct packed {
        redmule_regif__mcnfig2__y_offs__out_t y_offs;
    } redmule_regif__mcnfig2__out_t;

    typedef struct packed {
        logic [31:0] value;
    } redmule_regif__marith0__x_addr__out_t;

    typedef struct packed {
        redmule_regif__marith0__x_addr__out_t x_addr;
    } redmule_regif__marith0__out_t;

    typedef struct packed {
        logic [31:0] value;
    } redmule_regif__marith1__w_addr__out_t;

    typedef struct packed {
        redmule_regif__marith1__w_addr__out_t w_addr;
    } redmule_regif__marith1__out_t;

    typedef struct packed {
        logic [31:0] value;
    } redmule_regif__marith2__z_addr__out_t;

    typedef struct packed {
        redmule_regif__marith2__z_addr__out_t z_addr;
    } redmule_regif__marith2__out_t;

    typedef struct packed {
        redmule_regif__mcnfig0__out_t mcnfig0;
        redmule_regif__mcnfig1__out_t mcnfig1;
        redmule_regif__mcnfig2__out_t mcnfig2;
        redmule_regif__marith0__out_t marith0;
        redmule_regif__marith1__out_t marith1;
        redmule_regif__marith2__out_t marith2;
    } redmule_regif__hwpe_ctrl_job_dep__out_t;

    typedef struct packed {
        redmule_regif__hwpe_reserved__out_t reserved;
    } redmule_regif__hwpe_ctrl_job_indep__out_t;

    typedef struct packed {
        redmule_regif__hwpe_ctrl_mandatory__out_t hwpe_ctrl;
        redmule_regif__hwpe_ctrl_job_dep__out_t hwpe_job_dep;
        redmule_regif__hwpe_ctrl_job_indep__out_t hwpe_job_indep;
    } redmule_regif__out_t;

    typedef enum logic [2:0] {
        gemm_op_e__MATMUL = 'h0,
        gemm_op_e__GEMM = 'h1,
        gemm_op_e__ADDMAX = 'h2,
        gemm_op_e__ADDMIN = 'h3,
        gemm_op_e__MULMAX = 'h4,
        gemm_op_e__MULMIN = 'h5,
        gemm_op_e__MAXMIN = 'h6,
        gemm_op_e__MINMAX = 'h7
    } gemm_op_e_e;

    typedef enum logic [1:0] {
        gemm_fmt_e__Float8 = 'h0,
        gemm_fmt_e__Float16 = 'h1,
        gemm_fmt_e__Float8Alt = 'h2,
        gemm_fmt_e__Float16Alt = 'h3
    } gemm_fmt_e_e;
endpackage
