# Copyright 2021 OpenHW Group
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run functional regression checks
name: ci
on: [push, pull_request]

jobs:
  run-hwpe-tests:
    name: run-hwpe-tests
    runs-on: ubuntu-latest
    env:
      NUM_JOBS: 8
      Target: verilator
      REDMULE_COMPLEX: 0
      BENDER: ./bender
      Verilator: verilator
      VERILATOR_VERSION: "5.046"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Verilator (prebuilt)
      uses: veryl-lang/setup-verilator@v1
      with:
        version: ${{ env.VERILATOR_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v8.3.2

    - name: Install required tools
      run: |
        make riscv32-gcc
        make bender
        cd golden-model && source setup-py.sh && cd ..

    - name: Add installed tools to PATH
      run: |
        echo "$(pwd)/vendor/install/cargo/bin" >> $GITHUB_PATH
        echo "$(pwd)/vendor/install/riscv/bin" >> $GITHUB_PATH
        echo "$(pwd)/golden-model/venv/bin" >> $GITHUB_PATH

    - name: Run Tests
      run: |
        Target=verilator scripts/regression-list.sh

  # run-complex-tests:
  #   name: run-complex-tests
  #   runs-on: ubuntu-latest
  #   env:
  #     Target: verilator
  #     REDMULE_COMPLEX: 1
  #     BENDER: ./bender

  #   needs:
  #     install-tools
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       submodules: recursive

  #   - name: Install required tools
  #     run: |
  #       make bender
  #       make riscv32-gcc
  #       make verilator
  #       pip3 install numpy
  #       cd golden-model && source setup-py.sh && cd ..

  #   - name: Run Tests
  #     run: |
  #       source scripts/regression-list.sh
  #   - name: Upload Simulation Logs
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: simulation-logs
  #       path: |
  #         target/sim/**/transcript_*
